num = input('Número: ')
num = num.replace('', ' ').rstrip().lstrip()
num = num.split()
print(f'Unidade = {num[3]}')
print(f'Dezena = {num[2]}')
print(f'Centena = {num[1]}')
print(f'Milhar = {num[0]}')
